version: '2'
services:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password!
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress!
      MYSQL_HOST: ""

  web:
    image: kunitaya/apache24_php71:latest
    ports:
      - "10080:80"
      - "10443:443"
    depends_on:
      - db
    volumes:
      - ./httpd.conf:/etc/httpd/conf/httpd.conf
      - ./httpd_conf.d:/etc/httpd/conf.d
      - ./php.ini:/etc/php.ini
      - ./htdocs:/var/www/html
