version: '2'
services:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password!
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress!
      MYSQL_HOST: ""
    ports:
      - "13306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql

  web:
    build: ./docker
    hostname: wordpress.local
    privileged: true
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./htdocs:/var/www/html
