version: '2'
services:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password!
      MYSQL_DATABASE: kaikei
      MYSQL_USER: smrj
      MYSQL_PASSWORD: kaikei2017
      MYSQL_HOST: ""
    ports:
      - "13306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql

  web:
    image: kunitaya/apache24_php70:latest
    environment:
      DOCROOT: /var/www/html
      WP_LOCALE: ja
      CREATE_CONF: 0
      MYSQL_DATABASE: kaikei
      MYSQL_USER: smrj
      MYSQL_PASSWORD: kaikei2017
      MYSQL_HOST: db
    ports:
      - "10080:80"
      - "10443:443"
    depends_on:
      - db
    volumes:
      - ./startup.sh:/root/startup.sh
      - ./httpd.conf:/etc/httpd/conf/httpd.conf
      - ./httpd_conf.d:/etc/httpd/conf.d
      - ./php.ini:/etc/php.ini
      - ./htdocs:/var/www/html
    command: [bash, /root/startup.sh]
